[package]
name = "fend-core"
version = "1.5.8"
description = "Arbitrary-precision unit-aware calculator"
edition = "2024"
repository = "https://github.com/printfn/fend"
homepage = "https://github.com/printfn/fend"
keywords = ["calculator", "cli", "conversion", "math", "tool"]
categories = ["command-line-utilities", "mathematics", "science"]
license = "MIT"
readme = "README.md"

[dependencies]
# No external dependencies for fend-core!
